### ISSUE TITLE
Mods removed from database

### ISSUE THREAD

**Issue by joselitosn** [7D2DModLauncher/Database#1]
When using the launcher today, I noticed some mods I was playing in Alpha 19 are not showing. Looking at the [latest ModLauncher.sqlite](https://github.com/7D2DModLauncher/Database/blob/759485278f993037170845c8264e996336835ed9/ModLauncher.sqlite), I couldn't find any reference to the mods I used to play (Darkness Falls and War of the Walkers).

In case they are being removed, they are still mentioned in the [7D2DConfig repository](https://raw.githubusercontent.com/SphereII/7D2DConfig/master/Alpha19/Default.xml). But if possible, can you make it still appear for those who had it installed? Maybe in a different section, like "Other" or "Unsupported"?

**Comment by SphereII** [comment]
Thank you for the report. Gitlab is currently having trouble with some of the mods:  https://status.gitlab.com/

Once that's restored, they'll be re-listed. Sorry for the trouble.

**Comment by joselitosn** [comment]
Thank you. I appreciate the effort and dedication to keep the launcher updated for the community.

I guess it just seemed weird that even the mods I had installed disappeared.

**Comment by SphereII** [comment]
I would expect it as well. I'll look into it tomorrow
